name: MessageReplacer
version: @version@
main: kr.entree.messagereplacer.MessageReplacer
softdepend: [ProtocolSupport, ProtocolLib]
authors: [EntryPoint]
commands:
  messagereplacer:
    aliases: [mrep, mr]
